MUDM.-Presensimobile.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Flutter Build CI
+name: Android Build CI
 
 on:
   push:
@@ -20,19 +20,26 @@ jobs:
         distribution: 'zulu'
         java-version: '17'
 
-    - name: Set up Flutter
-      uses: subosito/flutter-action@v2
-      with:
-        channel: 'stable'
+    - name: Cari dan Berikan Izin Eksekusi gradlew
+      run: |
+        GRADLEW_PATH=$(find . -name gradlew -print -quit)
+        if [ -z "$GRADLEW_PATH" ]; then
+          echo "ERROR: File gradlew tidak ditemukan di folder mana pun!"
+          exit 1
+        fi
+        echo "gradlew ditemukan di: $GRADLEW_PATH"
+        chmod +x "$GRADLEW_PATH"
+        # Menyimpan folder gradlew agar bisa digunakan di langkah berikutnya
+        echo "GRADLE_DIR=$(dirname "$GRADLEW_PATH")" >> $GITHUB_ENV
 
-    - name: Install dependencies
-      run: flutter pub get
-
-    - name: Build Android APK
-      run: flutter build apk --release
+    - name: Build APK (Release)
+      run: |
+        cd ${{ env.GRADLE_DIR }}
+        ./gradlew assembleRelease
 
     - name: Upload APK Artifact
       uses: actions/upload-artifact@v4
       with:
-        name: release-apk
-        path: build/app/outputs/flutter-apk/app-release.apk
+        name: android-release-apk
+        path: |
+          **/build/outputs/apk/release/*.apk
